name: "Bug Report"
about: Report a bug in FrameLog
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: input
    attributes:
      label: Summary
      description: Short description of the bug
      placeholder: Crash when logging
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      placeholder: 1.0.0

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the bug
      placeholder: |
        1. Include FrameLog
        2. Call Logger::Add("")
        3. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What you expected to happen

  - type: checkboxes
    attributes:
      label: Affected Platforms
      options:
        - label: Windows
        - label: Linux
        - label: macOS
