name: "Feature Request"
about: Suggest a new feature or improvement for FrameLog
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: input
    attributes:
      label: Summary
      description: Short description of the feature
      placeholder: Add file logging
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation
      description: Why is this feature needed?

  - type: textarea
    attributes:
      label: Proposed Solution
      description: How should it work?

  - type: checkboxes
    attributes:
      label: Useful for
      options:
        - label: Embedded
        - label: Games
        - label: Desktop apps
        - label: Servers

  - type: dropdown
    attributes:
      label: Priority
      options: [Low, Medium, High, Critical]
